Various minor bugfixes
screepers/Screeps-Typescript-Declarations pull request #84
Opened 2016-12-29 21:34 UTC by ChrisKitching

2017-02-05 11:32 UTC, Dessix approved these changes

2017-02-05 11:32 UTC, Dessix commented on dist/screeps.d.ts
> +interface MoveToOpts extends FindPathOpts {
Acceptable, assuming there are no places without FindPathOpts included in MoveToOpts usage.

2017-02-05 11:33 UTC, Dessix requested changes
Approved pending conflict resolution and checking of changes involved.

2017-02-05 17:53 UTC, merged

2017-02-06 00:35 UTC, ChrisKitching commented on dist/screeps.d.ts
> +interface MoveToOpts extends FindPathOpts {
This formulation matches the manual:
http://support.screeps.com/hc/en-us/articles/203013212-Creep#moveTo

Under the definition of of `opts`, it explicitly states:
> Any options supported by Room.findPath method.

So: any code which is relying on MoveToOpts not containing members from FindPathOpts is wrong.

2017-02-06 06:49 UTC, Dessix commented on dist/screeps.d.ts
> +interface MoveToOpts extends FindPathOpts {
It has been merged, so thank you 👍