Add null return type to findClosest methods
screepers/Screeps-Typescript-Declarations pull request #88
Opened 2017-01-01 16:41 UTC by bigmike1020

RoomPosition.findClosest methods can return null if no objects match the filter.

2017-02-05 11:08 UTC, Dessix requested changes
This change integrates changes from ChrisKitching:storeCorrectness / PR #86 which have not been approved, and the requested changes should be merged separately. Aside from that, I've confirmed the correctness of the null status of the returns as indeed being null and not undefined. Please remove the unrelated changes before we can accept the submission.

2017-02-06 13:57 UTC, bigmike1020 commented
Thank you. I have updated the commits.

2017-02-06 20:43 UTC, Dessix requested changes
Please remove the changes that revert StoreDefinition updates, and you're clear for integration.

2017-02-06 20:43 UTC, Dessix commented on src/helpers.ts
> +    energy: number;
Please undo these changes, then recompile `dist` without them.

2017-04-19 01:12 UTC, closed without merging