Replace some of the constants with static types
screepers/Screeps-Typescript-Declarations pull request #94
Opened 2017-02-07 02:26 UTC by Sheeo

Makes for better type inference, since `const` declarations are inferred
to their narrowest type at declaration.

E.g. `const x = 5;` infers the type of `x` to be `5`, making the literal
`5` compatible.

Since types are generally widened without a problem, this shouldn't
be an incompatible change with anyones codebase -- although number type
literals are a relatively new typescript feature, so full utilization of
this may require TS 2.1.

2017-02-07 03:50 UTC, Dessix requested changes
Overall, I like it! I've noted a few minor stylistic changes, and some observations - We were missing some things. This is a big change, so I'd like multiple contributors' feedback on this (@anisoptera).

2017-02-07 03:50 UTC, Dessix commented on src/constants.ts
> +declare const EXTENSION_ENERGY_CAPACITY: {0: 50, 1: 50, 2: 50, 3: 50, 4: 50, 5: 50, 6: 50, 7: 100, 8: 200};
Can we match the style of `RAMPART_HITS_MAX` here?

2017-02-07 03:50 UTC, Dessix commented on src/constants.ts
>  declare const BODYPARTS_ALL: string[];
I'll see about adding this one in with my issue-#91 changes, which should present a unified type for many of these items.

2017-02-07 03:50 UTC, Dessix commented on dist/screeps.d.ts
> +declare const FIND_NUKES: 117;
Did we not have this one originally?

2017-02-07 14:52 UTC, Sheeo commented on dist/screeps.d.ts
> +declare const FIND_NUKES: 117;
Indeed, this was missing.

2017-02-07 18:40 UTC, Sheeo commented on src/constants.ts
> +declare const EXTENSION_ENERGY_CAPACITY: {0: 50, 1: 50, 2: 50, 3: 50, 4: 50, 5: 50, 6: 50, 7: 100, 8: 200};
Of course, done.

2017-02-07 23:51 UTC, Dessix approved these changes
Approved. Still need an approval from @anisoptera, @ags131, or @NhanHo before merge due to change scope.

2017-02-09 04:46 UTC, anisoptera commented
My one concern is what happens if my codebase runs in an environment with different universal constants. Does this affect the final code generation in any way?

If not, then I'm totally down for this. Thanks for the metric ton of work!

2017-02-09 04:55 UTC, Dessix commented
Type literals only affect the validity of operations on that type- from what I can tell, typescript doesn't consider multiple values of the same type as different types (Take a number and compare it against 1, the result isn't the interface of number differenced by the interface of 1 if it's false, or the interface of 1 if it's true). It should be fine because the types are elided, the only situation that would change here is when you change the values acceptable as members of unions of values, or if the value is limited on assignment. (You can't assign `3` to `1 | 2 | 4`, and if you change the type-literal of `MOVE` to ``Derp`` in your universe, `"move"` will no longer be a valid creep body part string literal, and `"Derp"` would be typed directly as `MOVE`). Inheritance/membership chains could also fail on types (see with MOVE- the reason for the issue is that we would be registering constants for each bodypart under a shared type which is simply a union of their individual types. This could be compensated for on a per-custom-environment basis with a second ambient declaration of the interface(s) or type(s) affected.

2017-02-09 04:56 UTC, anisoptera commented
Sounds about right, just wanted to make sure. 👍

2017-02-09 04:56 UTC, merged